### ISSUE TITLE
Header and navigation with no search or links

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#100]
Added a header and navigation with no links, and the padding is not there. 

![SCEHeader](https://user-images.githubusercontent.com/65776851/121095093-4bd21800-c7b5-11eb-9b62-79059d24f2e8.png)

**Comment by mwllr** [comment]
We should require the link for the main site title to go back to the home page! Should be default???

college of xyz doesn't have to link to anywhere, but site title does.

**Comment by mwllr** [comment]
Not sure how to test this..... link?? @bryanjonker-illinois

**Comment by bryanjonker-illinois** [comment]
Whoops. https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/nolinks/index.html

@mwllr -- just make sure it looks ok? I ran into this edge case when working on this, and wanted someone to take a look. Thanks.

**Comment by bryanjonker-illinois** [comment]
That's it -- I'll close the issue. Thanks.
