### ISSUE TITLE
Main nav -- SVG mobile needs to have a unique aria-label

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#103]
SVG mobile toggles in nav need to have unique description ("toggle about", "toggle research", etc.). Needs to pull from the anchor list.

**Comment by mwllr** [comment]
have accessibility expert check please.

**Comment by bryanjonker-illinois** [comment]
I sent a note to Keith to check.

**Comment by bryanjonker-illinois** [comment]
Talked with Keith, and he said it is good to close. Added only issue he found to bug #109.
