### ISSUE TITLE
Add 2 paragraphs to Formatting Page

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#106]
https://cdn.brand.illinois.edu/toolkit/2.0/examples/stylesheets/formatting/index.html

Can you add a paragraph of lorem ipsum after each of the lists? I need to see spacing after a list with more paragraphs.

**Comment by mattsharkey** [comment]
Test page at https://cdn.brand.illinois.edu/toolkit/dev/examples/stylesheets/lists/index.html

**Comment by mwllr** [comment]
on lists:
- make sure bullets and numbers of lists are same font color as body - gray. they look blue.
- also need spacing between the list and the next paragraph.
![Screen Shot 2021-06-25 at 11 42 36 AM](https://user-images.githubusercontent.com/54747669/123458611-d9ca4300-d5aa-11eb-9e3f-ffe66d99d4aa.png)
