### ISSUE TITLE
Footer: spacing is wrong in older browsers

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#113]
Spaces between sections are missing in browsers that don't support flex gap.

**Comment by mwllr** [comment]
looks like it is fixed - saw changes on my son's phone. (Can't get mine to show changes yet.)

![IMG_4559](https://user-images.githubusercontent.com/54747669/122605621-51ddb980-d03d-11eb-8e7b-68a286d09857.JPG)
