### ISSUE TITLE
New test page with sub items on side nav

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#121]
Make new test page: ACES/Research/Research Areas/Agriculture & Environment

- [ ] Need following sub-items under Research Areas in the side navigation: Agriculture and Environment, Family and Communities, Health and Wellness, Data and Technology.
- [ ] Add the following content to the page. (taken from https://aces.illinois.edu/research/areas/ag-env) (just the first section and under the orange subheading section - end before news starts. I don't even need images yet since we haven't defined any padding for them... ;)

Agriculture and Environment
Our agriculture and environment researchers work to improve food security, protect wildlife, ensure a clean water supply, develop climate change solutions, and bolster the health and sustainability of natural and managed systems.

These impacts are made possible through public and private investments, legislator support, multi-institutional partnerships, and the dedication of faculty and student scholars.  

Below, we showcase a fraction of our world-class research in the area of agriculture and the environment. You can also view a pdf version and subscribe to one of our ACES e-newsletters to stay abreast of new developments in ACES research.

Farmer mental health and COVID-19
Farmer in field

While popular media has covered some issues in agriculture related to COVID-19, to date no research evidence demonstrates impacts of the pandemic on the mental health of farmers, especially with regards to Illinois. Research has demonstrated that psychological distress among producers is associated with higher rates of injury as well as lower rates of adopting new technologies. Assisting in improving mental health may benefit producer safety and farm efficiency and production.

In a project at the very intersection of agriculture and health, ACES researchers Courtney Cuthbertson and Josie Rudolphi are collecting data from agricultural producers in Illinois about the impacts of COVID-19 on their day-to-day operations and finances, as well as on their mental health. So far, the team has collected over 2,300 responses.

Once completed, Illinois Extension educators will use the findings to share useful mental health information and resources, normalizing conversations about mental health to decrease stigma. Since COVID-19 stay-at-home orders were put into place, the researchers have collaborated with Extension educators Chelsea Harbach, Phillip Alberti, Karla Belzer, and Chelsey Byers Gerstenecker to create and offer three- to five-minute recorded segments called, "A Moment for Mental Health," during commercial agriculture webinars.

The project will also identify opportunities and barriers to training licensed medical providers, including mental health workers, primary care physicians, nurses, and others, in agricultural literacy. Agricultural producers may be hesitant to seek out mental health care due to shortages of mental health providers in their communities or due to stigma. Knowing mental health and other health providers have a background in or knowledge about agriculture may help reduce barriers and make it easier for producers to ask for help.

Funding: The researchers have applied for USDA NIFA Farm and Ranch Stress Assistance Network funding (potentially $7.2 million over three years).

ACES researchers:
Courtney Cuthbertson, Human Development and Family Studies
Josie Rudolphi, Agricultural and Biological Engineering
Chelsea Harbach; Phillip Alberti; Karla Belzer; and Chelsey Byers Gerstenecker, University of Illinois Extension

**Comment by mattsharkey** [comment]
@mwllr Is this still needed? What specifically does this test need to demonstrate?

**Comment by mwllr** [comment]
Not sure why we wanted this one....  Closing it...
