### ISSUE TITLE
Footer legal links

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#131]
Footer  nav slot, class, aria-lablel...should look like: 
<img width="1048" alt="Screen Shot 2021-07-13 at 2 16 35 PM" src="https://user-images.githubusercontent.com/54747669/125850144-8e46547b-db88-4726-958d-304575024726.png">

**Comment by mwllr** [comment]
Is there a way to tag Keith to add to this issue??

**Comment by mwllr** [comment]
Can we tag Keith or did someone email him to look at??

**Comment by bryanjonker-illinois** [comment]
@khays9  -- can you look at this? Thanks.
