### ISSUE TITLE
Footer - Social Media Icons

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#132]
The social media icons do not have an aria label which makes them blank.... Please tag Keith if possible.

<img width="763" alt="Screen Shot 2021-07-13 at 2 49 01 PM" src="https://user-images.githubusercontent.com/54747669/125863272-38af97d8-e3f5-4eef-acbe-137a32b3fae6.png">

**Comment by bryanjonker-illinois** [comment]
Sent a note to Keith

This is concerning https://github.com/web-illinois/toolkit/issues/132

The social media links don’t have ARIA labels, but they do have text inside the links that refer to the social media platform. These are hidden using the overflow, so they should be available to screen readers. Based on this, do we need ARIA labels, or would that be extra noise? Thanks.

**Comment by bryanjonker-illinois** [comment]
Ah -- yeah, I think that was an old version. Basically, whatever the person puts in the slot is what we're going to put into the footer. Here is how it currently looks at  https://cdn.brand.illinois.edu/toolkit/dev/examples/components/footer/default/index.html

![image](https://user-images.githubusercontent.com/65776851/131874904-700d3889-c64c-4189-8dd0-2cb2564bff24.png)

If this looks OK, I'll close this ticket. Thanks.

**Comment by khays9** [comment]
That code looks good to me. I second that we close the issue.
