### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#140]
- [x] remove animation in accordion please.
- [x] switch +/- to chevrons.

https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html

**Comment by bryanjonker-illinois** [comment]
@mwllr -- please review -- https://jonker.web.illinois.edu/accordion/

Thanks!

**Comment by mwllr** [comment]
Design group says it is good to go!! Great job.
