### ISSUE TITLE
Hero: increase bottom padding

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#153]
There should be more padding at the bottom than at the top.

**Comment by mwllr** [comment]
this looks better for now. I think we will want to revisit this once we see content below it. I am guessing we might want to add a little more spacing... Done for 2.1
![Screen Shot 2021-07-30 at 1 37 27 PM](https://user-images.githubusercontent.com/54747669/127698197-a2bc46f8-0a54-4cd4-930c-9a5b1ca9de52.png)
