### ISSUE TITLE
Hero -- add ability to add alt-text to images

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#157]
Create ability to add alt-text to hero image. Discussion in MS Teams about this 

[9:47 AM] Strong, Dena L
    I can see a particularly strong case for "this picture is of Professor Y and her grad student Z, in their lab doing cutting edge research on topic A" -- and in that case you DO want to know who the people are and what they're doign and  why this department is proud of them. But if it's a generic "here are some circuit boards because we didn't have any actual human relevant content here" image...

​[9:55 AM] Jonker, Bryan J
Dena -- what you are saying makes sense. However, the hero image has the option to put text to the image as part of the header. So if the picture is "Professor Y and her grad student Z in their lab doing cutting edge research on topic A", the heading title may be "Cutting edge research at the College of Zen Surrealism". At that point, when does the alt text become just repetition and noise. Not saying we shouldn't do this, just that it's something to think of (ETA: wow, the bold is really bold in MS Teams). 

​[9:57 AM] Strong, Dena L
    To me the difference is that the headline is quite unlikely to convey what the alt text would in terms of "this is professor X and her grad student Y doing this particular thing in their lab." The headlines usually cut out what people who knew their faces could see in terms of recognizing who was photographed - and the alt text could both restore that and provide those hits to Google.
    That is, of course, assuming you have an actually useful and relevant picture. If you've got stock photo circuit boards, in that case I totally agree that "" is your better option. I like to hope that people want to choose useful and relevant pictures! But I have an optimist and a cynic doing Alton Brown's boxing-nuns in my head right now. XD

**Comment by khays9** [comment]
Hero images are generally decorative in nature, with any text content providing the information. While I can see the case where the image is intended to convey information, I suspect that it will be a very rare instance on campus. Alt text is for users who are blind, so the primary deciding factor here would be if the additional information would provide important information for the user or would be additional noise that would interfere with them orienting to the page that just loaded.

I don't see any harm in providing the ability to add alt text--along with guidance on when it is appropriate to make a hero image informational--but the default would need to make the images decorative, I think.
