### ISSUE TITLE
Name structure problem

### ISSUE THREAD

**Issue by dlstrong** [web-illinois/toolkit#212]
https://github.com/web-illinois/toolkit/wiki/Data-attributes - It looks like the name standard here shifted from il-word to word-il. How hard is it to change that back to match the rest of the standard so that people don't have to remember out of their head "oh yeah wait this one thing is name-broken"?

**Comment by bryanjonker-illinois** [comment]
"data-*" is a fixed thing, so we can't really do that. The good news is the "data-il" is going to be fixed -- we shouldn't have anything else be X-il. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*
