### ISSUE TITLE
Documentation: Distinction between code contributors and the people who use the code

### ISSUE THREAD

**Issue by dlstrong** [web-illinois/toolkit#214]
The "Git branching and deployment" page (https://github.com/web-illinois/toolkit/wiki/Git-Branching-and-Deployment) has a clearly different audience than the other pages I found so far.

In the right hand nav, you see it's labeled Developers -- if you found the page by using the right nav.

If you DIDN'T find the page by using the right nav -- if you followed a link from another page or the Pages listing -- then you don't have that indicator unless you figure it out from context.

I want a way to make our audiences clearer within the pages themselves, so that people who are making their first website using this stuff don't find this page and go "oh dear God" and brace themselves and start trying to figure out how to do the developer thing even though it's not the thing that they need to do for what they're actually doing.

I don't see a way to "tag" or "label" wiki pages the way we can label issues or tag releases.

Does anyone know of a wiki-approved way to do this?

If not, where (preferably toward the top of the pages) can I add a new element identifying the audience for the page?

(This may be a meeting conversation.)

**Comment by mattsharkey** [comment]
This shouldn't be a part of the user documentation. I'll move this information into the code and remove the Wiki page.
