### ISSUE TITLE
Reduce size of chevon in compact navigation

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#22]
Reduce the size of the cheron in the open/close toggle button in the navigation in compact mode

**Comment by melissawaller78** [comment]
still a little light - will talk about at design group.

**Comment by melissawaller78** [comment]
@mattsharkey - can we make a tag: bring to design group??

**Comment by bryanjonker-illinois** [comment]
@mattsharkey, @melissawaller78 -- "design review" tag created

**Comment by melissawaller78** [comment]
see ticket #69

**Comment by melissawaller78** [comment]
what do I do when it is now a duplicate or needs to just reference the other one? back to to-do? just leave here?

**Comment by melissawaller78** [comment]
moving this over to next category.....
