### ISSUE TITLE
Incorrect focus colors in search

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#23]
The border color of the search widget should be blue (not orange) when it has focus

**Comment by melissawaller78** [comment]
change illini blue to industrial blue.

**Comment by bryanjonker-illinois** [comment]
Updated in latest build

**Comment by melissawaller78** [comment]
can we round the corners of the search box? and make it 4 px shorter overall?

**Comment by bryanjonker-illinois** [comment]
Updated with latest build

**Comment by bryanjonker-illinois** [comment]
Updated in latest build

**Comment by melissawaller78** [comment]
good. done with colors!
