### ISSUE TITLE
Use Pointer events rather than mouse events

### ISSUE THREAD

**Issue by jongund** [web-illinois/toolkit#238]
* [MDN pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)
* [W3C Pointer Event Spec](https://www.w3.org/TR/pointerevents2/)

**Comment by nhoyt** [comment]
[Pointer events - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events)
