### ISSUE TITLE
Image feature: remove "align" attribute

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#269]
The "align" attribute should be deprecated. Alignment should be controlled with CSS class and CSS variables.

**Comment by bryanjonker-illinois** [comment]
Chatted a bit with Matt - the "align" attribute currently modifies the HTML. Going to do a complete refactor to keep the HTML static and use CSS to manage the order regardless of HTML order (the image is role="presentation", which means it should not matter re: accessibility).
