### ISSUE TITLE
New component - Page Title Banner

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#293]
Design file for Page Title Banner:
https://xd.adobe.com/view/311aa738-e411-4a6f-bc4a-694b4cebeb87-6449/

Please mock up as a new component.

**Comment by bryanjonker-illinois** [comment]
New page title banner XD design file: https://xd.adobe.com/view/311aa738-e411-4a6f-bc4a-694b4cebeb87-6449/
