### ISSUE TITLE
Navigation formatting suggestions

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#294]
[3:18 PM] Davis, Jennifer Lee
    Hi, web component folks! 
I noticed a couple of design issues with the nav menu:  
1) the vertical alignment is off, with less space on the bottom. From a typographic perspective, you generally want a little bit more space on the bottom than the top for it to look correctly centered to the human eye, so this looks really awkward. It's especially helpful to have extra lower space for any menu items that have descenders, since these are mixed case.
2) the first menu item doesn't align with the block I because of its left padding— usually that would be zeroed out for the sake of the alignment.
Thanks for all the time you all are spending on these!

https://teams.microsoft.com/l/message/19:734981213bce44f2a0f31e98a560fe08@thread.tacv2/1640207930328?tenantId=44467e6f-462c-4ea2-823f-7800de5434e3&groupId=7ecdbcb2-4a6c-438d-828c-70287b84f487&parentMessageId=1640207930328&teamName=Website%20Implementation%20Guidelines%20Group&channelName=Web%20Components&createdTime=1640207930328

**Comment by mattsharkey** [comment]
These issues were brought to the design group
