### ISSUE TITLE
New component: Card

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#303]
This is a non-clickable card, based off of https://drupal.webtheme.illinois.edu/paragraphs/cards

**Comment by bryanjonker-illinois** [comment]
@mattsharkey -- thoughts for the code? I could see multiple options:

````
<il-card src="/_assets/images/hero-bg.jpg">
<h3>Student Life</h3>
<p>Animal sciences students extend their learning and career networks beyond
the classroom through internships, judging teams, student organizations, undergraduate research
projects with our faculty, as well as short- and long-term study abroad opportunities all over the world. </p>
<p><a href="#" class="il-button">Learn More</a></p>
</il-card>
````
The simplest option. 

````
<il-card src="/_assets/images/hero-bg.jpg">
<h3 slot="header">Student Life</h3>
<p>Animal sciences students extend their learning and career networks beyond
the classroom through internships, judging teams, student organizations, undergraduate research
projects with our faculty, as well as short- and long-term study abroad opportunities all over the world. </p>
<p slot="footer"><a href="#">Learn More</a></p>
</il-card>
````
This matches the clickable cards most closely, and allows the user to put lots of stuff in the header and footer. I'm leaning towards this. 

````
<il-card src="/_assets/images/hero-bg.jpg" href="#" linktext="Learn More">
<h3 slot="header">Student Life</h3>
<p>Animal sciences students extend their learning and career networks beyond
the classroom through internships, judging teams, student organizations, undergraduate research
projects with our faculty, as well as short- and long-term study abroad opportunities all over the world. </p>
</il-card>
````
This restricts the user from putting in HTML in the footer. I'm not a fan of this. 

The actual background would be controlled by CSS class.

**Comment by dlstrong** [comment]
I have a pretty big usability question on this. If the non-clickable cards look this much like the clickable cards, we're going to be confusing the heck out of users who will have no way of knowing when they hover over a thing whether or not the whole area or none of it is going to be clickable. If they've already gotten used to "I hover over a thing that looks like this and the whole thing becomes clickable," then the non-clickable one is going to look broken.

**Comment by mattsharkey** [comment]
Not a fan of the href + link text either. If the link goes in a footer slot, is it pinned to the bottom of the card?

I don't like "src" as an attribute for the image. It makes sense for an image tag, but here there's not enough context. It makes the image seem more important than it is, and not optional. Can we have an "image" slot?

**Comment by dlstrong** [comment]
I honestly thought we had pushed back and that the conversation had gone "hey yeah maybe we don't want to do this thing this way after all?" We have had a ton of meetings, and things kind of blur in my head after a certain number of them, but I think it's worth asking whether this is actually a thing we want to do in this particular way.

(I could swear I remember part of the conversation going 'instead of adding a new component, why don't we make more things optional on the clickable card'? I don't remember the verdict, though.)

**Comment by bryanjonker-illinois** [comment]
> (I could swear I remember part of the conversation going 'instead of adding a new component, why don't we make more things optional on the clickable card'? I don't remember the verdict, though.)

Tell me about it! I thought that conversation was about "clickable cards with images versus clickable cards without images". 

The "Progress" tab has the "Cards (non-clickable, with button inside)" as "Ready for Development", so maybe it just hasn't gotten moved back to one of the other buckets yet? https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/_djb2_msteams_prefix_1601640873?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3A663271f2a9dc4ed68f4ea0d707c62dba%40thread.tacv2%22%7D&groupId=7ecdbcb2-4a6c-438d-828c-70287b84f487&tenantId=44467e6f-462c-4ea2-823f-7800de5434e3

**Comment by bryanjonker-illinois** [comment]
Spoke with Melissa, and confirmed we're going ahead with the Cards component.

**Comment by bryanjonker-illinois** [comment]
Think we're leaning towards this?

````
<il-card>
<img slot="image" src="/_assets/images/hero-bg.jpg">
<h3 slot="header">Student Life</h3>
<p>Animal sciences students extend their learning and career networks beyond
the classroom through internships, judging teams, student organizations, undergraduate research
projects with our faculty, as well as short- and long-term study abroad opportunities all over the world. </p>
<p slot="footer"><a href="#">Learn More</a></p>
</il-card>
````

**Comment by mattsharkey** [comment]
I like it. I think the thing I like most about it is that if you forget to add all the slot attributes it wouldn't look great but it wouldn't look too broken.
