### ISSUE TITLE
New component: Image Feature with Overlay

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#304]
https://drupal.webtheme.illinois.edu/paragraphs/feature-box

**Comment by bryanjonker-illinois** [comment]
Proposed HTML format: 

````
<il-image-feature-with-overlay>
  <img name="image" src="xxxxxx">
  <h3>LAS Impact Award: Recognizing inspiring efforts during COVID-19</h3>
  <p>The College of LAS honors individuals and teams that have demonstrated service and sacrifice beyond expectations during the pandemic.</p>
  <p><a href="#" class="il-button">Celebrate the awardees</a></p>
</il-image-feature-with-overlay>
````

Classes available are il-theme-blue, il-theme-orange, il-align-right, il-align-left

@mattsharkey  -- thoughts?

**Comment by mwllr** [comment]
@bryanjonker-illinois  - from design meeting 1/27
- [ ] White theme - change header to blue
- [ ] tablet and mobile - change borders to match image feature - see XD or image feature
- [ ] merge into image feature as an option instead of stand alone component - talk to @mattsharkey
