### ISSUE TITLE
Looking for header guidance: multi-level attribution

### ISSUE THREAD

**Issue by karres-illinois** [web-illinois/toolkit#316]
Hi

I am looking for advice.  If I worked in the "College of Widgets" and was in a lab, group, etc called "Modern Widgets" and that lab had a special public facing/interacting project called "Modern Interactions with Widgets".  How should I list and style all of those items?

The examples I have seen so far seem to have, at most, two levels of attribution in the header block.  How should more levels of attribution be handled?

I am guessing something like:

College of Widgets
Modern Widgets
Modern Interactions with Widgets

With each line getting increasingly larger font size?

Should I risk the official ire of someone by removing the college or group name?

**Comment by bryanjonker-illinois** [comment]
Fielded question to design team. 

https://teams.microsoft.com/l/message/19:663271f2a9dc4ed68f4ea0d707c62dba@thread.tacv2/1645041581551?tenantId=44467e6f-462c-4ea2-823f-7800de5434e3&groupId=7ecdbcb2-4a6c-438d-828c-70287b84f487&parentMessageId=1645041581551&teamName=Website%20Implementation%20Guidelines%20Group&channelName=Design&createdTime=1645041581551

**Comment by mwllr** [comment]
@karres-illinois - There are ONLY TWO lines allowed in the header block.
It is up to each college to set their definition of using the college as the top level or the middle lab/group of modern widgets in this case. You may have even skipped the department in the college in your example... 

For multiple levels, that is addressed in the footer where you could have multiple listed, but it doesn't show hierarchy in the footer.

Here's an example that shows multiple colleges associated with this site, but there is only the option to add one/primary association in the header. Allowing multiple in the header will clog it up and make it less useful. You also have the option to not show the College in the header and only have the site title.

![Screen Shot 2022-02-16 at 4 50 02 PM](https://user-images.githubusercontent.com/54747669/154370970-a080a0d6-fc37-457e-aa6a-47bd599942cd.png)
