### ISSUE TITLE
Change header link color

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#33]
The links in the top-right corner of the header should be Illini Orange

**Comment by bryanjonker-illinois** [comment]
Need to flip colors

**Comment by bryanjonker-illinois** [comment]
Top menu is altgeld on hover-over

**Comment by melissawaller78** [comment]
top menu is illini orange on hover.
/ between links are illini orange too.

**Comment by bryanjonker-illinois** [comment]
Updated in latest build

**Comment by melissawaller78** [comment]
Please change these feature links to weight - 600 instead of 700.

**Comment by melissawaller78** [comment]
good. done
