### ISSUE TITLE
tables - showing different examples from code

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#340]
on the documentation tests for tables, it shows a responsive table and style that isn't the default style in the CSS.

https://cdn.toolkit.illinois.edu/2/examples/stylesheets/tables/index.html - show a responsive table

https://mwaller.web.illinois.edu/acc-color/tables.html - shows tables with no extra styling

Why are some blue headers and the responsive one isn't? Can we get cdn.toolkit page to show what actually happens when you put a table in or why are these different?

**Comment by bryanjonker-illinois** [comment]
Any column with a class="il-hide" will be hidden in a mobile view. Let me talk with Matt to see if this belongs in the CDN, toolkit help screen, or builder.

**Comment by bryanjonker-illinois** [comment]
This was discussed in the design group -- I think we're going to tear out the tables and revisit the whole process.
