### ISSUE TITLE
tables - the last <td> is not putting a right border

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#341]
![2022-04-20 17_08_15-Accordion on Version 2 7 _ U of I](https://user-images.githubusercontent.com/65776851/164333152-76d9b908-6479-4ac5-b4dc-b14e3612b4ae.png)

The first <th> puts a line to the left, the last <th> puts a line to the right, and all <td> does nothing. Need to change the <td> so it matches the <th>.

**Comment by mwllr** [comment]
Great! That's what it needed. Fixed.
![Screen Shot 2022-04-21 at 8 55 12 AM](https://user-images.githubusercontent.com/54747669/164473714-db564c9a-21a9-4226-b0dc-b93e67e09406.png)
