### ISSUE TITLE
Page title is overlapping over navigation title

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#346]
https://mcb.web.illinois.edu/departments/molecular-integrative-physiology/phd-molecular-integrative-physiology
<img width="300" alt="2022-05-05 15_10_17-PhD in Molecular   Integrative Physiology _ School of Molecular   Cellular Biolo" src="https://user-images.githubusercontent.com/65776851/167020017-6d5d9aad-f8ea-4df5-b8a3-3ab7ede286bd.png">

**Comment by bryanjonker-illinois** [comment]
Think this is a bug or unintended issue. Changing the title in the Page Title to z-index: 100 fixes the issue.

**Comment by trubach** [comment]
Hey @bryanjonker-illinois , could you expand/share a screenshot on what element you're adding the z-index: 100 to? I'm trying it on my local machine and not getting any results.

**Comment by bryanjonker-illinois** [comment]
Here's the fix that changed this. 

https://github.com/web-illinois/toolkit/commit/8378d2a6cb9e1befb6c22dc9f124f5bae15ea835#diff-0055e50e821b92102e495dd2f8561c9eca344d903022eada788cbf15420e73b4R35

This has been implemented in 2.8.0 and we created a test case to check this at 
https://cdn.toolkit.illinois.edu/2/examples/components/page-title/withheader/index.html

If you need this added to an earlier version of the toolkit, let us know and we can do that.

**Comment by trubach** [comment]
Ah, thanks for the clarification. It wasn't clear to me that the fix was included in a new release. I can update the toolkit on our site and I'll report back if there's any issues.
