### ISSUE TITLE
Add space between dropdown subnav items

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#35]

**Comment by melissawaller78** [comment]
adding a few more pixels - 5>7 and 10>12 spacing between each.

**Comment by bryanjonker-illinois** [comment]
Done with the latest build

**Comment by melissawaller78** [comment]
Add 4px before first item in drop down list. Remove 4px after the last item.

**Comment by bryanjonker-illinois** [comment]
Updated in latest build

**Comment by melissawaller78** [comment]
I believe this is good to go. done.
