### ISSUE TITLE
Change alignment for right-side navigation dropdowns

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#36]
Rules for navigation dropdown alignment:

- Less than 4 items: all menus left-aligned
- 5 items: first 4 are left-aligned, last item is right-aligned
- More than 5 items: last 2 items are right-aligned, rest are left-aligned

**Comment by bryanjonker-illinois** [comment]
Right now, it's set so you can mark items as "left" (default) or "right". We probably do want to make it automatic.

**Comment by melissawaller78** [comment]
looks good. can you spin up examples with 4, 5, 6, and 7 nav items?

**Comment by melissawaller78** [comment]
Still weird - let's talk about this.... how/what to do....

![Screen Shot 2021-05-21 at 2 43 07 PM](https://user-images.githubusercontent.com/20865753/119190415-f242bd00-ba42-11eb-98e4-49720dd828db.png)
![Screen Shot 2021-05-21 at 2 43 18 PM](https://user-images.githubusercontent.com/20865753/119190416-f2db5380-ba42-11eb-8a43-763b26851c71.png)
![Screen Shot 2021-05-21 at 2 43 58 PM](https://user-images.githubusercontent.com/20865753/119190468-04246000-ba43-11eb-970e-abac53a74095.png)
