### ISSUE TITLE
section nav - move text left 5 px

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#374]
For section nav items, remove 5px padding/margin on left side. Then the text should align with the About in the main nav mune item text.
![Screen Shot 2022-08-12 at 3 08 35 PM](https://user-images.githubusercontent.com/54747669/184435179-7ca92fac-510e-4030-8550-20c402e8ffdf.png)

**Comment by bryanjonker-illinois** [comment]
https://dev.toolkit.illinois.edu/jonker/IssuesFor2-12Milestone/examples/components/layout/sidebar-components/index.html

**Comment by mwllr** [comment]
Approved!
![Screen Shot 2022-09-09 at 4 17 09 PM](https://user-images.githubusercontent.com/54747669/189447145-92236723-df62-4bcc-9f91-2b2be21d5eb9.png)
