### ISSUE TITLE
il-header compact mode override

### ISSUE THREAD

**Issue by magjarvis** [web-illinois/toolkit#384]
On the MCB website, https://mcb.illinois.edu/, the nav menu is filled to the max with nav items. Currently, the header is set to switch to compact (using the mobile/hamburger menu) mode at around 988px, but by that time the last two menu items get cut-off. We would need a way to possibly override the component and force the header to go into compact mode a little sooner, around 1225px.

**Comment by bryanjonker-illinois** [comment]
Talking with Matt -- there is a workaround. 

`<il-header full="min-width: 800px">` should switch the code from compact to full at 800px; Experimenting, it looks like it doesn't use the media query, but locks it to compact. Likewise, `<il-header compact="max-width: 800px;>" locks it to full.
