### ISSUE TITLE
Site titles and campus wordmark should be blue

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#4]
Sites titles and campus wordmark should be illini-blue, not black. (primary and secondary)

**Comment by melissawaller78** [comment]
also, should hover/focus to Illini Orange

**Comment by bryanjonker-illinois** [comment]
Please check on https://uiuc-toolkit-test.s3.us-east-2.amazonaws.com/samples/2.0/index.html -- need to do a hard refresh.
