### ISSUE TITLE
Image feature 

### ISSUE THREAD

**Issue by sydbethflowers** [web-illinois/toolkit#420]
Something that would be nice to add to our image feature component would be the ability to center align the blue box. Currently only left and right alignments are supported. I can modify it to make it mostly centered but would be even better to have this option in the component builder.

![Screenshot 2023-02-06 at 3 24 27 PM](https://user-images.githubusercontent.com/69855580/217091510-52b634bb-7cad-44e3-9ae6-6f25468a879b.png)

**Comment by bryanjonker-illinois** [comment]
Added an "il-align-center" to the version 3 of the il-feature (was il-image-feature). 
You can also manually change the value of the --il-feature--main--flex-grow to change the percentage.
