### ISSUE TITLE
Don't require Node 14 to fix M1 mac compatibility

### ISSUE THREAD

**Issue by VladislavEkimtcov** [web-illinois/toolkit#466]
Currently, the toolkit specifies Node 14 and minor versions as a dependency. This causes compatibility issues when building on M1 Macs, as Node 14 does not support M1 platform natively.

The following pull request resolves this issue and allows building on M1 Macs:
https://github.com/web-illinois/toolkit/pull/465

**Comment by mattsharkey** [comment]
This will be fixed in the 3.0 release
