### ISSUE TITLE
read.me missing an ending tag?

### ISSUE THREAD

**Issue by sydbeth** [web-illinois/toolkit#485]
```
<link rel="stylesheet" href="https://cdn.toolkit.illinois.edu/3.0.0-alpha.1/toolkit.css">
<script src="https://cdn.toolkit.illinois.edu/3.0.0-alpha.1/toolkit.mjs" type="module">
```

**Comment by sydbeth** [comment]
Or maybe something else missing in the instructions? I get a CORS error when I try to add this script to my local dev environment to test the new version of the toolkit.

Mac OS Ventura
Firefox Browser & Chrome
Wordpress Development

**Comment by bryanjonker-illinois** [comment]
Add to the README.md how to edit the vite.config.js file and index.js file and run ``npx vite build --config *newfile*.config.js`` to build custom files
