### ISSUE TITLE
Remove blue dashes for hover/focus for header

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#49]
Header hover/focus should be color only.

**Comment by melissawaller78** [comment]
removed on all but the university .. Svg.

**Comment by melissawaller78** [comment]
on mobile/tablet - remove from apply/give at bottom of list in drop down nav.

**Comment by bryanjonker-illinois** [comment]
Updated with latest build

**Comment by melissawaller78** [comment]
The feature links (apply/donate...) should be underlined on hover/focus also. My apologies.

**Comment by bryanjonker-illinois** [comment]
Updated with latest build.

**Comment by melissawaller78** [comment]
now we have a solid blue line..... needs to go.  Uof I and menu
![Screen Shot 2021-05-20 at 11 45 58 AM](https://user-images.githubusercontent.com/20865753/119017842-0ca46a00-b961-11eb-91c3-6eb597399901.png)
![Screen Shot 2021-05-20 at 11 45 53 AM](https://user-images.githubusercontent.com/20865753/119017853-0f06c400-b961-11eb-834b-10ac6c79f5cd.png)
![Screen Shot 2021-05-20 at 11 46 28 AM](https://user-images.githubusercontent.com/20865753/119017863-10d08780-b961-11eb-8918-3d35767a28f9.png)

**Comment by bryanjonker-illinois** [comment]
@melissawaller78 -- I wanted to confirm this from an accessibility perspective. Remove the outlines?

**Comment by melissawaller78** [comment]
Altgeld is back! Way to go. thanks. done.

Removing outlines for now..... testing with accessibility.... we return to this later if necessary. done for now.
