### ISSUE TITLE
Hamburger menu should show focus and change icons

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/toolkit#50]
From three lines to X, color change per zeplin

**Comment by bryanjonker-illinois** [comment]
Changed color, but going to need help with the SVG and hiding the span. I'm rubbish at SVG.

**Comment by mwllr** [comment]
look great to me.  all links hover/focus to Altgeld. Chevrons look great, move correctly and color changes are good.
![Screen Shot 2021-05-26 at 10 40 35 AM](https://user-images.githubusercontent.com/54747669/119689872-d5c1ce80-be0e-11eb-80f6-02d91717e9c0.png)
