### ISSUE TITLE
Section navigation: adjust spacing & font sizes

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#58]
Full view:
* Level 1: 20px font size, 10px padding top & bottom
* Level 2: 18px font size
* Level 3+: 16px
* Level 4+: increase left padding by 4px

Compact view:
* Level 2: decrease right padding by 4px, increase bottom padding of contents (ul) by 4px
* Level 4+: increase right padding by 4px

**Comment by melissawaller78** [comment]
Full view:

Level 1: 20px font size, 10px padding top & bottom - would like to be about 50 px tall like main navigation.

**Comment by melissawaller78** [comment]
left to right spacing on indents is good. spacing of gray box around programs of study needs to be much smaller. I want that top box to only be 50px tall.
>>Level 1 (Programs of Study): 20px font size, 10px padding top & bottom - would like to be about 50 px tall like main navigation.

**Comment by mwllr** [comment]
looks like the hover/focus is still Illini Orange instead of Alltgeld??

**Comment by mwllr** [comment]
spacing looks good... still want to test this out with content on the page...

**Comment by mwllr** [comment]
Color looks good, but still want to see it with text on a full page to finalize spacing. Thanks!
