### ISSUE TITLE
Section nav: toggle color on hover/focus

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#59]
Should be Illini Orange instead of Altgeld

**Comment by melissawaller78** [comment]
Sorry, color changed back to Altgeld. Please change.

**Comment by mwllr** [comment]
hover/focus color is Altgeld Orange...

**Comment by mwllr** [comment]
I'm still not seeing the darker orange for hover/focus.

![Screen Shot 2021-05-27 at 12 37 32 PM](https://user-images.githubusercontent.com/54747669/119871712-57d1f600-bee8-11eb-89d0-025e7c885932.png)
