### ISSUE TITLE
Section nav: change top-level background color

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#60]
Should be #F0F0F0. Applies to Level 1 item in full view and "In this section" heading in compact view

**Comment by melissawaller78** [comment]
done. - although Illini orange hover on gray isn't accessbile - talking about that today.

**Comment by melissawaller78** [comment]
using Altgeld - new ticket: ticket #68

**Comment by melissawaller78** [comment]
going to mark done. is now Altgeld.
