### ISSUE TITLE
placement and logos moving around...

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#66]
When I compare:

https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/multiple/index.html
https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/nomenu/index.html
https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/variant/index.html

The size of college changes block I moves down.... weird.

**Comment by bryanjonker-illinois** [comment]
This is happening because of the following code:

    getWidth() {
        const w = this.offsetWidth;
        if (w < 300) {
            return 'narrow';
        }
        return 'wide';
    }

This is causing the some primary units to be 14px, some to be 16px, depending on the width of the name. Should we be changing the font size? May require a phone conversation.

**Comment by melissawaller78** [comment]
font size should not change.

**Comment by mwllr** [comment]
The only thing I see is that the default header is showing slightly higher on the page than the other two (multiple and variant). Font sizes are matching!
When comparing default and multiple, the pipe changes size.
