### ISSUE TITLE
Change all nav hover/focus colors to Altgeld Orange...

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#68]
So sorry about this..... for hover and focus states:
-change university of... to altgeld and add underline.
-change primary and secondary site titles to altgeld
-change feature links (apply/donate) to altgeld, also change "/"

Nothing in header/navigation should use Illini Orange except Block I and top orange bar above university of..

**Comment by melissawaller78** [comment]
done. good.

**Comment by bryanjonker-illinois** [comment]
Moved to done -- closed
