### ISSUE TITLE
Changes to compact nav

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#69]
quite a few little changes to compact nav:
-main nav items: about, academics.... Font-size: 20px, Font-weight: 600,  hover/focus - background changes to white when you hover/focus on the text for the item (about, academics,...) and hover/focus is altgeld
-No border on buttons, hover/focus goes to white background and again, no border and changes to altgeld chevron. 
-Chevron size increased to be 1/3 height of line
-lines between the main items go to 1px and use same gray under news when it is expanded currently.
![Screen Shot 2021-05-20 at 11 25 43 PM](https://user-images.githubusercontent.com/20865753/119081999-caac1000-b9c2-11eb-8990-088f87828093.png)

![Unknown](https://user-images.githubusercontent.com/20865753/119081882-89b3fb80-b9c2-11eb-8095-6a941390a3ca.png)

**Comment by mwllr** [comment]
![Screen Shot 2021-05-21 at 4 46 35 PM](https://user-images.githubusercontent.com/54747669/119201336-51f59400-ba54-11eb-9142-a9b6e482fcdf.png)
gray space above first part, no gray above chevron part. zoom in...

**Comment by mwllr** [comment]
in compact nav - when you expand an item (international) the gray line under international should be same weight as other lines.
![Screen Shot 2021-05-24 at 12 10 16 PM](https://user-images.githubusercontent.com/54747669/119383578-1db6e900-bc89-11eb-8459-68cf98d0de80.png)

**Comment by mwllr** [comment]
Also, the white areas behind chevrons are different sizes.... and all should be max height of the element:
they shouldn't jog/overlap at all...
![Screen Shot 2021-05-27 at 3 16 29 PM](https://user-images.githubusercontent.com/54747669/119891444-9672ab00-befe-11eb-9b2d-848ab75cbad4.png)
make white area taller:
![Screen Shot 2021-05-27 at 3 16 45 PM](https://user-images.githubusercontent.com/54747669/119891497-a4c0c700-befe-11eb-9f91-409b513eb541.png)

**Comment by bryanjonker-illinois** [comment]
Moved to done -- closing
