### ISSUE TITLE
menu has too high of z index

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#71]
The menu's z-index is too high. Covers our drupal menu items.

and mobile menu z-index isn't high enough as well as the appended ul list of the buttons (apply, give, etc) that's in the upper-right hand corner of the website

![image](https://user-images.githubusercontent.com/20865753/119159071-82214080-ba1c-11eb-9bbe-ff000714f30f.png)
![image (1)](https://user-images.githubusercontent.com/20865753/119159090-85b4c780-ba1c-11eb-9faf-eff5f21a6643.png)

**Comment by bryanjonker-illinois** [comment]
We need to work with Drupal and Wordpress team to determine the range of z-indexes that we are allowed to use.

**Comment by mattsharkey** [comment]
All the elements in the header should be scoped to the <il-header> element, so you should be able to fix the first part just by giving the Drupal admin menu a higher z-index than the <il-header> element:

````
.admin-menu { z-index: 100 }
il-header { z-index: 99 }
````

That _should_ ensure that everything in the admin menu is on top of everything in the header

I'm not sure I understand the second part about the mobile nav & the upper right links

**Comment by mwllr** [comment]
@wrg20  - please add to this when you have a moment.
