### ISSUE TITLE
footer - legal section

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#74]
-Change focus/hover to 1px dashed border instead of 2 it is currently at.
-Add more spacing to the legal links - 35px between links.
-Add a margin/padding for right side of legal section so no links go within 80 (up to 767px), 100 px of the right side inside the page margins (767 plus).
-Change left and right margins on all up to 767 to 20 instead of 30. (should match header)

![Screen Shot 2021-05-21 at 11 52 38 AM](https://user-images.githubusercontent.com/20865753/119172505-ac2e2f00-ba2b-11eb-83ff-421369df2292.png)
![Screen Shot 2021-05-21 at 11 52 43 AM](https://user-images.githubusercontent.com/20865753/119172510-acc6c580-ba2b-11eb-99e4-975fcabb828d.png)
![Screen Shot 2021-05-21 at 11 52 47 AM](https://user-images.githubusercontent.com/20865753/119172511-acc6c580-ba2b-11eb-9399-552b3eed9f12.png)

**Comment by melissawaller78** [comment]
![Uploading Screen Shot 2021-05-21 at 11.57.56 AM.png…]()

**Comment by melissawaller78** [comment]
Since the back to top button goes over the footer, we need to make sure the legal links don't go behind there since you won't be able to scroll on the smaller screens to get to them without the back to top button covering them up.

**Comment by mwllr** [comment]
done. margins are good. footer links don't go all the way to right to allow back to top. legal links focus/hover is good and spacing is good.
![Screen Shot 2021-05-21 at 5 39 24 PM](https://user-images.githubusercontent.com/54747669/119204661-a0f2f780-ba5b-11eb-9f05-fbdc4c89a6eb.png)

**Comment by bryanjonker-illinois** [comment]
Moved to done -- closed
