### ISSUE TITLE
Site title, block I, and alignment

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#77]
Zeplin: https://zpl.io/a3EvZmx

Updated how the branding aligns with the pipe on tablet. Also, shows what happens when we have really really long titles.....

**Comment by mwllr** [comment]
Need examples of this to test out too.

**Comment by mwllr** [comment]
looks good from tests shown at design meeting. Something we can watch for and tweak for 2.1 if necessary.
