### ISSUE TITLE
Site title doesn't link/hover on header - compact

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#79]
https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/default/index.html

**Comment by melissawaller78** [comment]
well. anytime there is only the primary site title, when 2 are listed, they both link....

**Comment by bryanjonker-illinois** [comment]
It is built so the site title can be a link or not. 

In https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/default/index.html, it is implemented without a link:

``` 
        <il-unit-wordmark>
            <h1>College of Agricultural, Consumer & Environmental Sciences</h1>
        </il-unit-wordmark>
```
In the multiple version, it is implemented with links:

```
        <il-unit-wordmark>
            <p class="il-primary-unit"><a href="/">College of Education </a></p>
            <h1><a href="/">Council on Teacher Education</a></h1>
        </il-unit-wordmark>
```

**Comment by mwllr** [comment]
Site title must always link to the home page! REQUIRED. 
Secondary site (smaller above primary) title doesn't have to link.
Add to example headers.
(need by ITPF)

**Comment by bryanjonker-illinois** [comment]
We'll put a note in the usage guide, but this is a part of the usage, not hardcoded here.
