### ISSUE TITLE
Main Nav - keyboard with arrows/links

### ISSUE THREAD

**Issue by melissawaller78** [web-illinois/toolkit#80]
We should be able to change the color of the chevron when we tab on keyboard to the main menu item. The chevron should change to orange as well as the text. 
![Screen Shot 2021-05-21 at 4 40 04 PM](https://user-images.githubusercontent.com/20865753/119201007-aba98e80-ba53-11eb-8a43-d02fbbdd0978.png)
![Screen Shot 2021-05-21 at 4 40 09 PM](https://user-images.githubusercontent.com/20865753/119201010-aba98e80-ba53-11eb-9e43-fed9f08299c8.png)

**Comment by mwllr** [comment]
(need by ITPF)

**Comment by bryanjonker-illinois** [comment]
Spoke with Keith about this, and from an accessibility perspective, we'll need to retool how this works. 

On focus, the menu should auto-expand, don't move to next child automatically (which is correct), use left and right keys to move across.

**Comment by bryanjonker-illinois** [comment]
We ended up rewriting how this is done to meet accessibility requirements. Keith confirmed. Added only issue he found to bug #109.

**Comment by khays9** [comment]
Yes. That should work fine.

**Comment by mattsharkey** [comment]
Remaining issue is covered by #201
