### ISSUE TITLE
formatting page - add padding

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#83]
https://cdn.brand.illinois.edu/toolkit/2.0/examples/stylesheets/formatting/index.html

currently, you have 20 and 10px for padding, make them 30 and 20 for all headings, please.
![Screen Shot 2021-05-24 at 11 26 38 AM](https://user-images.githubusercontent.com/54747669/119377616-f0673c80-bc82-11eb-95ba-b906313462cb.png)

**Change to:**

![Screen Shot 2021-05-24 at 11 25 15 AM](https://user-images.githubusercontent.com/54747669/119377531-daf21280-bc82-11eb-8b70-13a7813f2048.png)

**Comment by mwllr** [comment]
Also, can we add a few links in the paragraphs and maybe even some of the headings? (need by ITPF)

Also, add the drop cap at some point (doesn't have to be done for ITPF)

**Comment by mattsharkey** [comment]
Here's a test page with a whole bunch of headings: https://cdn.brand.illinois.edu/toolkit/2.0/examples/stylesheets/headings/index.html

**Comment by mwllr** [comment]
@mattsharkey Is there a reason that the paragraph line height doesn't display correctly on this page? It's throwing me off.

**Comment by mattsharkey** [comment]
The default line height was different from the paragraph line height. Should be fixed now

**Comment by mwllr** [comment]
Looks good now. done.

![Screen Shot 2021-06-02 at 12 57 22 PM](https://user-images.githubusercontent.com/54747669/120529411-189d1c80-c3a2-11eb-8b3b-5407eb35ef10.png)
