### ISSUE TITLE
Footer: About Cookies button/code

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#86]
How or will the cookies button function like Wordpress with the flyout menu stuff? or is that not part of the component?

![Screen Shot 2021-05-27 at 3 29 44 PM](https://user-images.githubusercontent.com/54747669/119892964-64624880-bf00-11eb-94ab-37ea01a62df1.png)

**Comment by bryanjonker-illinois** [comment]
Yeah, that's not part of the component per-se. You can add the cookie button, but how it operates depends on the third-party product.
