### ISSUE TITLE
Header : Margins

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#88]
As we worked through page content, we have a bit of a change to the margins on the header. If you need me to clarify any of this, please ask!!

Header content stays in 1140 - except top orange bar and gray nav bar.)

Essentially, we have the following:
-Content area is 1140.
-desktop from 992-1199 px t - keep margins at 30.
-then we have 1200+. the content centers in 1140 content area for header/footer and basic paragraphs. Margins are split between what is left. Some things extend past the content area like hero, features, cards, and a few more. 
green margins are what we have had set. Blue margins are new margin that is whatever is left of 1140px container.
![Page Margin - 1100](https://user-images.githubusercontent.com/54747669/119901288-55cd5e80-bf0b-11eb-8035-fa50fafa5cac.png)
![Page Margin - 1241+ – 1](https://user-images.githubusercontent.com/54747669/119901289-55cd5e80-bf0b-11eb-898f-9cf9db5cbc9f.png)

**Comment by mwllr** [comment]
![Uploading Page Margin - 1241+.png…]()

**Comment by mattsharkey** [comment]
@mwllr I added the max content width back to the header & footer. Can you tell me if it looks right to you?

**Comment by mwllr** [comment]
between 1200 and 1240 is weird- stays at 50, but expands  ... Not needed, just 1200plus on header. Just need to go from 30px margin at 1199 to centering of 1140 at 1200+.  

![Screen Shot 2021-06-02 at 1 53 21 PM](https://user-images.githubusercontent.com/54747669/120536743-1212a300-c3aa-11eb-94c9-e738e43e4f38.png)


Footer looks right though.
