### ISSUE TITLE
Accessibility on Header from Keith

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#90]
FYI - Keith is out until Tuesday 6/1.

Everything looks good, excepting the following points:
 
The color contrast ratios are fine
The entire header must be in a <header> region, or in a <div> with role=”banner”
The main site navigation must be in a <nav> region, or in a <div> with role=”navigation”
Each navigation region must have a unique label, supplied by the aria-label attribute in this case. There are two in the header: The main navigation, and the Apply / donate / Contact links
Remember not to use the words “navigation” or “menu” in the region labels. Screen readers add the word “navigation”
The Search box and button should be in a container with role=”search”. Just wrap it in a <div> and that should do.
The svg used for the search icon must have a role=”image” and an appropriately descriptive alternative text—supplied via the aria-label attribute
Remember not to use the word “image” in the alt description.
In general, all images used as the only content for a link or button must have a role of image
<img width="1560" alt="Unknown-1" src="https://user-images.githubusercontent.com/54747669/120001161-1cdbcb00-bf99-11eb-978c-6f4902cbd234.png">

Template banner with bookmarklets showing how the banner, search, and navigation regions should be used.

**Comment by mwllr** [comment]
well - keith's message actually reads: 
![Screen Shot 2021-05-28 at 9 45 47 AM](https://user-images.githubusercontent.com/54747669/120001550-85c34300-bf99-11eb-8a1b-7f8c88cf64c9.png)

**Comment by bryanjonker-illinois** [comment]
Some of the landmarks are being set within the web component. Will this work? New version is pushed.

**Comment by mwllr** [comment]
@bryanjonker-illinois  - email Keith Hays. He will be able to approve this one. I can't give final approval on this.

**Comment by bryanjonker-illinois** [comment]
Good conversation with Keith on this, he gave a go-ahead to close this. 

Three more issues -- I'm going to create these:
1. "aria-haspopup" needs to be added to links, aria-label needs to be added to top nav section in demos. 
2. svg mobile toggles in nav need to have unique description ("toggle about", "toggle research", etc.)
3. keyboard access for desktop view needs to revisited -- auto-expand on focus, don't move to next child automatically (which is correct), use left and right keys to move across.
