### ISSUE TITLE
search box on iphone

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#91]
Here is some funky display for the search box on my iPhone... rounded pill inside a box? lol
![Screen Shot 2021-05-28 at 1 57 23 PM](https://user-images.githubusercontent.com/54747669/120030274-def09e00-bfbc-11eb-9265-73dd85755c59.png)

**Comment by bryanjonker-illinois** [comment]
That is funky. https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

**Comment by mwllr** [comment]
looks good on my iphone for the toolkit test page.
doesn't come though on my dev site using the dev components.
maybe other people can also test this one out????
