### ISSUE TITLE
toolkit display page

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#92]
I don't know what value they add to users since the rest is now built out??
Do we want to remove the following on https://cdn.brand.illinois.edu/toolkit/2.0/examples/index.html:
components/navigation/compact-collapsed | Navigation (compact view, all submenus collapsed) | 2021-04-27 23:29:03
-- | -- | --
components/navigation/compact-expanded | Navigation (compact view, one submenu expanded) | 2021-04-27 23:29:03
components/navigation/default-collapsed | Navigation (default view, all submenus collapsed) | 2021-04-27 23:29:03
components/navigation/default-expanded

**Comment by mattsharkey** [comment]
These are still needed for automated tests
