### ISSUE TITLE
Section nav: specify current page (aria-current)

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#93]

**Comment by mwllr** [comment]
Where can I see something working?

**Comment by mattsharkey** [comment]
https://cdn.brand.illinois.edu/toolkit/dev/examples/pages/aces-research-safety/index.html

**Comment by mwllr** [comment]
combining with issue #116 
nav bar - why is chevron blue? Should be orange on active state too.
![Screen Shot 2021-06-18 at 2 47 30 PM](https://user-images.githubusercontent.com/54747669/122609898-5bb6eb00-d044-11eb-83ab-2b660cbcde5e.png)

**Comment by mwllr** [comment]
looks good.
![Screen Shot 2021-06-25 at 11 41 16 AM](https://user-images.githubusercontent.com/54747669/123458120-47c23a80-d5aa-11eb-81cf-286909f413a6.png)
