### ISSUE TITLE
Site Title as H1 and more

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#94]
From Keith - Good catch!  I can’t believe I missed that.  
The department name should be an H1, along with the title in the page body.  
The home page of a site should only have the H1 in the banner. The <title> element in the <head> must be a combination of some of text in the H1 in the banner and that in the page body. Usually, it should be most specific to lease specific. To use the attached screen shot as an example, an appropriate title for the About page would be “About | Council on Teacher Education.”
 
Another important point about heading use is that they should be visible in the page as a general rule. If it is not desired to have a visible heading for a page region, use aria-label instead. If there is not appropriate region or element in that spot for an aria-label, it is an indication that you either do not need a heading there or need to make it visible for all users.

<img width="1560" alt="Unknown" src="https://user-images.githubusercontent.com/54747669/120513198-a6244080-c391-11eb-9868-582f7621332e.png">

**Comment by mattsharkey** [comment]
Where does this need to be fixed? On this page, COTE is already an H1: https://cdn.brand.illinois.edu/toolkit/2.0/examples/components/header/multiple/index.html

**Comment by bryanjonker-illinois** [comment]
Talked with Keith, good to close
