### ISSUE TITLE
hover/focus on links in headings and body paragraphs

### ISSUE THREAD

**Issue by mwllr** [web-illinois/toolkit#96]
Please remove the hover/focus dotted/dashed **blue** line from the links in the body. (and ANYWHERE else they might show up :)

![Screen Shot 2021-06-02 at 12 53 39 PM](https://user-images.githubusercontent.com/54747669/120529073-b80ddf80-c3a1-11eb-84a0-999b8661b2cc.png)
![Screen Shot 2021-06-02 at 12 53 48 PM](https://user-images.githubusercontent.com/54747669/120529077-b93f0c80-c3a1-11eb-997d-6cb1eda50d56.png)

**Comment by mwllr** [comment]
Shows on : https://cdn.brand.illinois.edu/toolkit/2.0/examples/stylesheets/headings/index.html
and
https://cdn.brand.illinois.edu/toolkit/2.0/examples/pages/aces-research-safety/index.html

**Comment by bryanjonker-illinois** [comment]
Removed anything we're doing. The browser may add focus, and I left that as is.

**Comment by mwllr** [comment]
We need to set it so it specifically does nothing. Don't let the browser set it.

**Comment by mwllr** [comment]
Great. done.
![Screen Shot 2021-06-09 at 10 16 10 AM](https://user-images.githubusercontent.com/54747669/121381945-c8770a80-c90b-11eb-88a1-9306e4a72368.png)
![Screen Shot 2021-06-09 at 10 16 04 AM](https://user-images.githubusercontent.com/54747669/121381946-c90fa100-c90b-11eb-920a-a65ef4ba80a7.png)
